subject : play_again0.o play_again1.o play_again2.o play_again3.o play_again4.o
	gcc -o play_again0 play_again0.o
	gcc -o play_again1 play_again1.o
	gcc -o play_again2 play_again2.o
	gcc -o play_again3 play_again3.o
	gcc -o play_again4 play_again4.o

play_again0.o : play_again0.c
	gcc -c play_again0.c

play_again1.o : play_again1.c
	gcc -c play_again1.c

play_again2.o : play_again2.c
	gcc -c play_again2.c

play_again3.o : play_again3.c
	gcc -c play_again3.c

play_again4.o : play_again4.c
	gcc -c play_again4.c

all: subject

clean: rm -f *.o subject
